### ISSUE TITLE
IllegalArgumentException: Service Intent must be explicit

### ISSUE THREAD

**Issue by hollyhook** [googlesamples/android-ElizaChat#1]
try to run eliza chat on handheld samsung S4 Android 5.0.1 and wearable Moto 360 Android 5.0.2 build with Android studio

04-25 10:36:41.660  26701-26701/com.example.android.wearable.elizachat D/AndroidRuntime﹕ Shutting down VM
04-25 10:36:41.660  26701-26701/com.example.android.wearable.elizachat E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.android.wearable.elizachat, PID: 26701
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.wearable.elizachat/com.example.android.wearable.elizachat.MainActivity}: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.example.android.wearable.elizachat.INCOMING }
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2693)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2760)
            at android.app.ActivityThread.access$900(ActivityThread.java:177)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5944)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
     Caused by: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.example.android.wearable.elizachat.INCOMING }
            at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:2052)
            at android.app.ContextImpl.startServiceCommon(ContextImpl.java:2090)
            at android.app.ContextImpl.startService(ContextImpl.java:2065)
            at android.content.ContextWrapper.startService(ContextWrapper.java:533)
            at com.example.android.wearable.elizachat.MainActivity.startResponderService(MainActivity.java:63)
            at com.example.android.wearable.elizachat.MainActivity.onCreate(MainActivity.java:58)
            at android.app.Activity.performCreate(Activity.java:6289)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2760)
            at android.app.ActivityThread.access$900(ActivityThread.java:177)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5944)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
04-25 10:41:41.713  26701-26701/com.example.android.wearable.elizachat I/Process﹕ Sending signal. PID: 26701 SIG: 9

**Comment by ekux44** [comment]
Reproduced on a Nexus5 running Lollipop 5.1 paired with a LG G watch running 5.0.

A quick StackOverflow search suggests that Android 5.0 dropped support for implicit intents, so this sample is broken on all Lolipop+ devices...

**Comment by codingjeremy** [comment]
This sample has been deprecated.
